StudentCRUD/StudentCRUD/Models/myClassInfo.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Web;

namespace StudentCRUD.Models
{
    public class myClassInfo
    {

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public myClassInfo()
        {
            this.Students = new HashSet<myStudents>();
        }

        
        public int Class_Id { get; set; }
        [DisplayName("Standard")]
        public Nullable<int> Standard { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<myStudents> Students { get; set; }
    }
}

StudentCRUD/StudentCRUD/Models/myStudents.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace StudentCRUD.Models
{
    public class myStudents
    {
        public int Student_Id { get; set; }

        [Required(ErrorMessage ="Please Enter Name of Student")]
        public string Name { get; set; }

        [Required(ErrorMessage = "Please Enter Name of Student Address")]
        public string Address { get; set; }

        
        public Nullable<int> Class_Id { get; set; }

        public virtual myClassInfo ClassInfo { get; set; }
    }
}

StudentCRUD/StudentCRUD/Controllers/StudentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using StudentCRUD;
using StudentCRUD.Models;

namespace StudentCRUD.Controllers
{
    public class StudentsController : Controller
    {
        private CRUD_OperationsEntities db = new CRUD_OperationsEntities();

        // GET: Students
        public ActionResult Index()
        {
            List<myStudents> myStudentsList = new List<myStudents>();
            var students = db.Students.Include(s => s.ClassInfo);
            foreach (var student in students)
            {
                myClassInfo myClassInfo = new myClassInfo()
                {
                    Class_Id = student.ClassInfo.Class_Id,
                    EndDate = student.ClassInfo.EndDate,
                    Standard = student.ClassInfo.Standard,
                    StartDate = student.ClassInfo.StartDate
                };

                myStudents myStudent = new myStudents()
                {
                    Student_Id = student.Student_Id,
                    Name = student.Name,
                    Address = student.Address,
                    ClassInfo = myClassInfo,
                    Class_Id = myClassInfo.Class_Id,

                };
                myStudentsList.Add(myStudent);
            }
            return View(myStudentsList.ToList());
        }

        // GET: Students/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Student student = db.Students.Find(id);
            if (student == null)
            {
                return HttpNotFound();
            }
            return View(student);
        }

        // GET: Students/Create
        public ActionResult Create()
        {
            if (!ModelState.IsValid)
            {
                return View(ModelState);
            }
            ViewBag.Class_Id = new SelectList(db.ClassInfoes, "Class_Id", "Standard");
            return View();
        }

        // POST: Students/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Student_Id,Name,Address,Class_Id")] myStudents student)
        {
            if (ModelState.IsValid)
            {

                Student myStudent = new Student()
                {
                    Name = student.Name,
                    Address = student.Address,
                    Class_Id = student.Class_Id
                };

                db.Students.Add(myStudent);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.Class_Id = new SelectList(db.ClassInfoes, "Class_Id", "Standard", student.Class_Id);
            return View(student);
        }

        // GET: Students/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Student student = db.Students.Find(id);
            if (student == null)
            {
                return HttpNotFound();
            }

           
            myStudents myStudent = new myStudents()
            {
                Student_Id = student.Student_Id,
                Name = student.Name,
                Address = student.Address,
                Class_Id = student.Class_Id,

            };

            ViewBag.Class_Id = new SelectList(db.ClassInfoes, "Class_Id", "Standard", student.Class_Id);
            return View(myStudent);
        }

        // POST: Students/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Student_Id,Name,Address,Class_Id")] myStudents student)
        {
            if (ModelState.IsValid)
            {


                Student myStudent = new Student()
                {
                    Student_Id = student.Student_Id,
                    Name = student.Name,
                    Address = student.Address,
                    Class_Id = student.Class_Id

                };

                db.Entry(myStudent).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Class_Id = new SelectList(db.ClassInfoes, "Class_Id", "Standard", student.Class_Id);
            return View(student);
        }

        // GET: Students/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Student student = db.Students.Find(id);
            if (student == null)
            {
                return HttpNotFound();
            }
            return View(student);
        }

        // POST: Students/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Student student = db.Students.Find(id);
            db.Students.Remove(student);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

StudentCRUD/StudentCRUD/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Students CRUD operations", "Index", "Students", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Students")</li>
                    
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

StudentCRUD/StudentCRUD/Views/Students/Create.cshtml
@model StudentCRUD.Models.myStudents

@{
    ViewBag.Title = "Create";
}

    <h2>Add new student</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Student</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ClassInfo.Standard, "Standard", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Class_Id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Class_Id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

StudentCRUD/StudentCRUD/Views/Students/Delete.cshtml
@model StudentCRUD.Student

@{
    ViewBag.Title = "Delete";
}

    <h2>Delete student</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Student</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

        <dt>
            @Html.HiddenFor(model => model.ClassInfo.Class_Id)
        </dt>

        <dd>
            @Html.HiddenFor(model => model.ClassInfo.Class_Id)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

StudentCRUD/StudentCRUD/Views/Students/Details.cshtml
@model StudentCRUD.Student

@{
    ViewBag.Title = "Details";
}

    <h2>Student Details</h2>

<div>
    <h4>Student</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

        <dt>
            @Html.HiddenFor(model => model.ClassInfo.Class_Id)
        </dt>

        <dd>
            @Html.HiddenFor(model => model.ClassInfo.Class_Id)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Student_Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

StudentCRUD/StudentCRUD/Views/Students/Edit.cshtml
@model StudentCRUD.Models.myStudents

@{
    ViewBag.Title = "Edit";
}

    <h2>Edit student details</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Student</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Student_Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ClassInfo.Standard, "Standard", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Class_Id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Class_Id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

StudentCRUD/StudentCRUD/Views/Students/Index.cshtml
@model IEnumerable<StudentCRUD.Models.myStudents>

@{
    ViewBag.Title = "Index";
}

<h2>All Students</h2>

<p>
    @Html.ActionLink("Add new student", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Address)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ClassInfo.Standard)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Address)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ClassInfo.Standard)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Student_Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Student_Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Student_Id })
        </td>
    </tr>
}

</table>